Controllers/CoursesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KulaMVC.Models;
using KulaMVC.Data;
using Microsoft.AspNetCore.Authorization;
namespace KulaMVC.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses
        [Authorize(Roles = "Admin, Instructor, Student")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Course.ToListAsync());
        }
        [Authorize(Roles = "Admin, Instructor, Student")]
        // GET: Courses/Details/5
        public async Task<IActionResult> Details(string id)
        {
            ViewData["collection"] = id;
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Module.Where(m => m.CollectionID == id).ToListAsync();
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin, Instructor")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CollectionID,Title,ShortDescription,ImageUrl,CreatedAt,Uploader,published,visibility")] Course course)
        {
            course.ID = Guid.NewGuid().ToString();
            course.CollectionID = Guid.NewGuid().ToString();
            course.CreatedAt = (int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return Redirect($"/Courses/Details/{course.ID}");
                //return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin, Instructor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Instructor")]
        public async Task<IActionResult> Edit(string id, [Bind("ID,CollectionID,Title,ShortDescription,ImageUrl,CreatedAt,Uploader,published,visibility")] Course course)
        {
            if (id != course.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin, Instructor")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(string id)
        {
            return _context.Course.Any(e => e.ID == id);
        }
    }
}

Controllers/ModulesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KulaMVC.Models;
using KulaMVC.Data;
using Microsoft.AspNetCore.Authorization;
namespace KulaMVC.Controllers
{
    [Authorize]
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModulesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Modules
        [Authorize(Roles="Admin, Instructor, Student")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Module.ToListAsync());
        }
        [Authorize(Roles="Admin, Instructor, Student")]
        public async Task<IActionResult> Preview(string CollectionID, string moduleID){
            var modules=await _context.Module.Where(r=>r.CollectionID==CollectionID).ToListAsync();
            if(moduleID==null){
                try{
                    var modelItem =await _context.Module.Where(r=>r.CollectionID==CollectionID).FirstOrDefaultAsync();
                    ViewData["Title"]=modelItem.Title;
                    ViewData["ShortDescription"]=modelItem.ShortDescription;
                    ViewData["LongDescription"]=modelItem.LongDescription;
                    ViewData["Video"]=modelItem.Video;
                }
                catch{
                    //
                }
                return View(modules);
            }
            var model =await _context.Module.Where(r=>r.ID==moduleID).FirstOrDefaultAsync();
            ViewData["Title"]=model.Title;
            ViewData["ShortDescription"]=model.ShortDescription;
            ViewData["LongDescription"]=model.LongDescription;
            ViewData["Video"]=model.Video;
            return View(modules);
        }
        // GET: Modules/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Module
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // GET: Modules/Create
        [Authorize(Roles="Admin, Instructor")]
        public IActionResult Create(string CollectionID)
        {
            ViewData["CollectionID"]=CollectionID;
            return View();
        }

        // POST: Modules/Create
        [Authorize(Roles="Admin, Instructor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CollectionID,language,Title,ShortDescription,LongDescription,Video,Uploader,Iat")] Module @module)
        {
            @module.ID=Guid.NewGuid().ToString();
            @module.Iat=(int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
            if (ModelState.IsValid)
            {
                _context.Add(@module);
                await _context.SaveChangesAsync();
                return Redirect($"/Modules/Preview?CollectionID={@module.CollectionID}");
                //return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles="Admin, Instructor")]
        public async Task<IActionResult> Edit(string id, string moduleID)
        {
            if (id == null)
            {
                return NotFound();
            }
            var @module = await _context.Module.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Modules/Edit/5
        [Authorize(Roles="Admin, Instructor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ID,CollectionID,language,Title,ShortDescription,LongDescription,Video,Uploader,Iat")] Module @module)
        {
            if (id != @module.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                 @module.Iat=(int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
                try
                {
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect($"/Courses/Details/{@module.CollectionID}");
                //return View(@module);
            }
            return View(@module);
        }

        // GET: Modules/Delete/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Module
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [Authorize(Roles="Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var @module = await _context.Module.FindAsync(id);
            _context.Module.Remove(@module);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ModuleExists(string id)
        {
            return _context.Module.Any(e => e.ID == id);
        }
    }
}

Views/Courses/Create.cshtml
@model KulaMVC.Models.Course

@{
    ViewData["Title"] = "Create";
}

<div>
    <h1>Create a new course</h1>
</div>
<h3>Course Information</h3>
<div class="course">
<form asp-action="Create" enctype="multipart/form-data">
    <div class="input-group mb-3">
        <input type="text" asp-for="Title" id="course-Title" required="" maxlength="50"
               class="form-control" placeholder="Enter course Title">
    </div>
    <div class="input-group mb-3">
        <input type="text" asp-for="ShortDescription" id="course-description" required=""
               maxlength="200" class="form-control" placeholder="Enter short description">
    </div>
    <div class="mb-3">
        <label for="file" class="form-label">Upload a picture for the course</label><input class="form-control form-control-sm" onchange="handleFileUpload(this)" id="file" type="file">
    </div>
    <div>
        <input type="text" asp-for="ImageUrl" id="ImageUrl" hidden>
    </div>
    <h3>Publish information</h3>
    <p><b>Publish Now: </b>This course will be available immedIately.</p>
    <p>
        <b>Publish Later: </b>This course will not be available immedIately. You will be able to publish it after
        modules
        have been added.
    </p>
    <div>
        <select asp-for="published" asp-items="Html.GetEnumSelectList<Publish>()" class="form-control">
            <option selected="selected" value="">Please select</option>
        </select>
    </div>
    <h3>Visibility Information</h3>
    <p><b>Public: </b>Everyone who is signed in can access this course.</p>
    <p><b>Private: </b>Only people you add by email will have access to the course.</p>
    <div>
        <select asp-for="visibility" asp-items="Html.GetEnumSelectList<Visible>()" class="form-control">
            <option selected="selected" value="">Please select</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>
</div>
<script>
    const handleFileUpload = async (e) => {
        var input = document.getElementById("file");
        var files = input.files;
        const formdata = new FormData();
        formdata.append("image", files[0], files[0].name);
        const requestOptions = {
            method: 'POST',
            body: formdata,
            redirect: 'follow'
        };
        await fetch("https://api.imgbb.com/1/upload?key=8d0a7e3689b931e211b03dbd58eab571", requestOptions)
            .then(response => response.json())
            .then((result) => {
                document.getElementById('ImageUrl').value = result.data.url;
            })
    }
</script>

Views/Courses/Delete.cshtml
@model KulaMVC.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h3>@Model.Title</h3>
<img src="https://i.ibb.co/9stx1C6/goal.png" class="rounded mx-auto d-block" style="max-height: 115px;">
<div>
    @Model.ShortDescription
</div>
<div>
    <span>Last Modified:
        @{
            System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
            dtDateTime = dtDateTime.AddSeconds(@Model.CreatedAt).ToLocalTime();
        }
        @dtDateTime
    </span>
</div>
<div>
    All modules assocIated with this course will also be deleted.
</div>
<h5>Are you sure you want to delete this course?</h5>
<form asp-action="Delete">
    <input type="hidden" asp-for="ID" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>

Views/Courses/Details.cshtml
@model IEnumerable<KulaMVC.Models.Module>

@{
    ViewData["Title"] = "Details";
}
<div class="course">
<a asp-controller="Modules" asp-action="Create" asp-route-CollectionID=@ViewData["collection"]>Add Modules</a>
</div>
<div class="modules">
    @{
        var count = 0;
        @foreach (var item in Model)
        {
            count++;
            <div>
                <div>
                    <h4>@count. @item.Title</h4>
                    <p>@item.ShortDescription</p>
                </div>
                <div>
                    <a asp-controller="Modules" asp-action="Edit" asp-route-id="@item.ID" class="btn btn-info">Edit</a>
                    <a asp-controller="Modules" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-danger">Delete</a>
                </div>
            </div>
            <hr />
        }
    }
</div>

Views/Courses/Edit.cshtml
@model KulaMVC.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<div class="course">
    <form asp-action="Edit">
        <div>
            <div>
                <h1><b>Edit Course</b></h1>
            </div>
        </div>
        <a asp-action="Details" asp-route-id="@Model.ID">Edit Modules</a>
            <h4>@Model.Title</h4>
            <div>
                <label asp-for="Title" class="control-label"><b>Update the course Title.</b></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div>
                <label class="control-label"><b>Language. (default: English)</b></label>
                <input id="language" class="form-control" type="text" readonly="" value="en">
            </div>
            <div class="form-floating textarea mb-3">

                <textarea asp-for="ShortDescription" class="form-control"></textarea>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div>
                <input type="text" asp-for="ImageUrl" id="ImageUrl" hidden>
            </div>
            <div class="form-group">
                <label asp-for="published" class="control-label"><b>Publish information.</b></label>
                <select asp-for="published" asp-items="Html.GetEnumSelectList<Publish>()" class="form-control">
                    <option selected="selected" value="">Please select</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="visibility" class="control-label"><b>Visibility information</b></label>
                <select asp-for="visibility" asp-items="Html.GetEnumSelectList<Visible>()" class="form-control">
                    <option selected="selected" value="">Please select</option>
                </select>
            </div>
            <img alt="" id="image-source" src="@Model.ImageUrl" />
            <div class="mb-3">
                <label for="file" class="form-label"><b>Upload a picture for the course</b></label>
                <input class="form-control form-control-sm" onchange="handleFileUpload(this)" id="file" type="file" />
            </div>
            <div>
                <input type="submit" value="Save">
            </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    const handleFileUpload = async (e) => {
        var input = document.getElementById("file");
        var files = input.files;
        const formdata = new FormData();
        formdata.append("image", files[0], files[0].name);
        const requestOptions = {
            method: 'POST',
            body: formdata,
            redirect: 'follow'
        };
        await fetch("https://api.imgbb.com/1/upload?key=8d0a7e3689b931e211b03dbd58eab571", requestOptions)
            .then(response => response.json())
            .then((result) => {
                alert("Image uploaded successfully.")
                document.getElementById('ImageUrl').value = result.data.url;
            })
    }
</script>

Views/Courses/Index.cshtml
@model IEnumerable<KulaMVC.Models.Course>
@using Markdig
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Index";
}
<div>
    <img b-h1z1mxik6a="" class="logo" src="https://i.ibb.co/1GgrKCJ/goat.png" alt="logo">
    <h1>Welcome to Kula Learn</h1>
</div>
<div>
    <div>
        We offer beginner and more advanced courses.
    </div>
    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Instructor"))
    {
        <a class="create-new-course" asp-action="Create">Create New Course</a>
    }
    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <a class="create-new-course" asp-action="Create">Create New Course</a>
    }
</div>
<div class="courses">
    @foreach (var item in Model)
    {
        <div class="course">
            <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
            <img src="@item.ImageUrl" />
            @{
                var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
                var hString = Markdown.ToHtml(@item.ShortDescription!, pipeline);
                <div>@Html.Raw(hString)</div>
            }
            <div>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Student"))
                {
                    <a asp-route-CollectionID="@item.ID" asp-controller="Modules" asp-action="Preview">View Course</a>
                }
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Instructor"))
                {
                    <a asp-route-CollectionID="@item.ID" asp-controller="Modules" asp-action="Preview">Preview</a>
                    <a asp-route-id="@item.ID" asp-action="Edit">Edit</a>
                }
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <a asp-route-CollectionID="@item.ID" asp-controller="Modules" asp-action="Preview">Preview</a>
                    <a asp-route-id="@item.ID" asp-action="Edit">Edit</a>
                    <a asp-route-id="@item.ID" asp-action="Delete">Delete</a>
                }
            </div>
            <div>
                Created at:
                @{
                    System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
                    dtDateTime = dtDateTime.AddSeconds(item.CreatedAt).ToLocalTime();
                }
                @dtDateTime
            </div>
            <div>Last modified by: <b>Instructor</b></div>
        </div>
    }
</div>